language: ruby
script: "bundle exec rspec"
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
  - 2.3.4
  - 2.4.1
services:
  - redis-server
email:
  recipients:
    - piotrek@okonski.org
  on_success: change
  on_failure: always
